title: '$o1eks@litus.io ~ $'
description: "O|eks L:tus"
url: https://oreksu.com

header_pages:
  - pages/index.md
  - pages/contact.md
  - pages/setup.md

style: dark
listen_for_clients_preferred_style: true

footer: 'you can find me on other social by `oreksu` or `orreksu`'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
