title: '$o1eks@litus.io ~ $'
description: "O|eks L:tus"
baseurl: ""
url: https://oreksu.com

header_pages:
  - pages/index.md
  - pages/contact.md
  - pages/setup.md

style: dark

footer: you can find me on other social by `oreksu` or `orreksu`

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
