title: '$o1eks@litus.io ~ $'
description: "o1eks website"
baseurl: ""
url: "https://litus.io"

header_pages:
  - pages/index.md
  - pages/contact.md
  - pages/setup.md

style: dark

footer: 'follow me on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: o1eks/jekyll-theme-console

theme: jekyll-theme-minimal